version: "3.3"
services:
  elasticsearch:
    image: elasticsearch:6.8.8
    environment:
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    ports:
      - 9200:9200
  mongo:
    image: mongo:4.0.18
    ports:
      - 27017:27017
